spring:
  application:
    name: shoppingMall

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: local   # 기본 활성 프로파일

jwt:
  secret: bXlTdXBlclNlY3JldEtleUZvckp3dDEyMzQ1Njc4OTA=

logging:
  level:
    org.springframework.web: DEBUG
    com.example.shoppingmall: DEBUG
